#!/usr/bin/env bash
# =============================================================================
# Transform 1: Remove committed zips and generated site from git tracking
# =============================================================================
# What this does:
#   1. Adds docs_src/downloads/, site/downloads/, site/content/, _site/
#      to .gitignore (these are all regenerated by build scripts)
#   2. Removes them from git index (keeps files on disk so local dev still works)
#   3. Also gitignores the site/ custom portal output (not deployed by CI)
#
# After running:
#   git add -A && git commit -m "chore: stop tracking generated zips and site output"
# =============================================================================
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== Transform 1: Remove committed generated outputs ==="
echo ""

# ── Step 1: Update .gitignore ──────────────────────────────────────
echo "Step 1: Updating .gitignore..."

# Check what's already there so we don't duplicate
ADDITIONS=""

add_if_missing() {
    local pattern="$1"
    local comment="$2"
    if ! grep -qxF "$pattern" .gitignore 2>/dev/null; then
        ADDITIONS="${ADDITIONS}\n${comment}\n${pattern}"
    else
        echo "  (already present: $pattern)"
    fi
}

add_if_missing "docs_src/downloads/" "# Generated zip downloads (rebuilt by prep_mkdocs.py)"
add_if_missing "site/" "# Custom portal output (rebuilt by build_site.py, not deployed)"
add_if_missing "_site/" "# MkDocs build output"

if [ -n "$ADDITIONS" ]; then
    printf "\n# Generated build outputs%b\n" "$ADDITIONS" >> .gitignore
    echo "  Added entries to .gitignore"
else
    echo "  .gitignore already up to date"
fi

# ── Step 2: Remove from git index (keep on disk) ──────────────────
echo ""
echo "Step 2: Removing generated files from git tracking..."

remove_from_index() {
    local path="$1"
    if git ls-files --error-unmatch "$path" &>/dev/null 2>&1; then
        git rm -r --cached "$path"
        echo "  Untracked: $path"
    elif [ -d "$path" ] && git ls-files "$path" | grep -q .; then
        git rm -r --cached "$path"
        echo "  Untracked: $path"
    else
        echo "  (not tracked: $path)"
    fi
}

remove_from_index "docs_src/downloads"
remove_from_index "site"

# ── Summary ────────────────────────────────────────────────────────
echo ""
echo "=== Transform 1 Complete ==="
echo ""
echo "Files removed from git index (still on disk for local dev)."
echo "Zips will be regenerated by prep_mkdocs.py during CI build."
echo ""
echo "Verify with:"
echo "  git status                       # should show deleted (from index) + .gitignore modified"
echo "  git diff --cached --stat         # confirm only deletions + .gitignore"
echo ""
echo "Then commit:"
echo "  git add -A"
echo "  git commit -m 'chore: stop tracking generated zips and site output'"
echo ""
echo "After push, verify GitHub Pages still deploys correctly"
echo "(prep_mkdocs.py generates fresh zips during CI)."
